### PR TITLE
Create task_description.html

### PR DESCRIPTION
**Pull request by tempest67**

### CODE REVIEW

**Comment by Bryukh** [comment]
Which one to merge? This or https://github.com/Bryukh-Checkio-Tasks/checkio-mission-pangram/pull/4?

And please look at the last line.

**Comment by tempest67** [comment]
#3 and #4 are the same ,it is my first translation and I did not manage and use the pull function properly. the last line should be removed , how can I re-edit it ?

**Comment by Bryukh** [comment]
> how can I re-edit it ?

Just edit again and add commit. It will be added

But don't worry - I will fix it. Thanks!

**Comment by tempest67** [comment]
Thank's , I have now done several translation . let's hope it will be useful for the community.

**Pull request merged**
